---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: secrets-probe-pipeline
spec:
  params:
    - name: pipeline-debug
      default: "0"
  workspaces:
    - name: pipeline-ws
  tasks:
    - name: extract-repository-url
      taskRef:
        name: toolchain-extract-value
      params:
        - name: expression
          # if a params.repository is given, it takes precedence
          value: '. as $toolchain | ["$(params.repository)"] | if .[0]=="" then $toolchain | .services[] | select(.toolchain_binding.name=="repo") | .dashboard_url else .[0] end'
        - name: pipeline-debug
          value: $(params.pipeline-debug)
    - name: secrets-probe
      taskRef:
        name: secrets-probe
      params:
        - name: repository
          value: $(tasks.extract-repository-url.results.extracted-value)
      workspaces:
        - name: workspace
          workspace: pipeline-ws      