---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: secrets-probe-pipeline
spec:
  params:
    - name: pipeline-debug
      default: "0"
  workspaces:
    - name: pipeline-ws
  tasks:
    - name: secrets-probe
      taskRef:
        name: secrets-probe
      params:
        - name: repository
          value: "https://github.com/huayuenh/mix"
      workspaces:
        - name: workspace
          workspace: pipeline-ws      