---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: secrets-probe
spec:
  params:
    - name: continuous-delivery-context-secret
      default: secure-properties
    - name: pipeline-debug
      default: "0"
    - name: repository
  results:
    - name: output
      description: output from tests
  workspaces:
    - name: workspace
      description: A workspace where the app is to be expected
      mountPath: /artifacts
  steps:
    - name: run-check
      image: ibmcom/pipeline-base-image
      workingDir: /artifacts
      script: |
        #!/bin/bash
        echo "running"
        git clone $(params.repository)
        ls